# Mon containerFile
FROM ubi8/ubi:8.5
MAINTAINER Alex
LABEL description="A custom Apache container based on UBI 8"

RUN yum install -y httpd && \
    yum clean all
RUN echo "Hello from ContainerFile" > /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]

